# stage production: set FLASK URL (modify settings.py) to api.nilportugues.com/translate/1.0/
stages:
  - build

docker_image:
    stage: build
    image: registry.gitlab.com/registry.docker.nilportugues.com/python3-ubuntu
    environment:
        - production
    script:
        - echo 'Rename .py.prod files to .py'
        - echo 'Run the build script'
        - sh build.sh
        - echo 'Build the docker image...'