version: '2'

services:
  translate_api:
    build: ./docker
    container_name: translate_api
    volumes_from:
      - translate_api_build
    ports:
      - "8001:80"

  translate_api_build:
    image: tianon/true
    volumes:
      - ./docker/translate_api-0.1.tar.gz:/tmp/build.tar.gz
