# Flask settings
# Using 127.0.0.1 is important.
FLASK_SERVER_NAME = '127.0.0.1:8080'
FLASK_DEBUG = True

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = False
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# Swagger
SWAGGER_UI_ENABLED = True
